name: modrinthosting
services:
  postgres_db:
    image: postgres:15-alpine
    container_name: labrinth-postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: labrinth
      POSTGRES_PASSWORD: labrinth
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: labrinth
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'labrinth']
      interval: 3s
      timeout: 5s
      retries: 3

  typesense0:
    image: typesense/typesense:30.1
    container_name: labrinth-typesense0
    restart: on-failure
    ports:
      - '127.0.0.1:8108:8108'
    volumes:
      - typesense-data:/data
    command: --data-dir=/data --api-key=modrinth --enable-cors
    healthcheck:
      test: ['CMD-SHELL', "bash -lc '</dev/tcp/127.0.0.1/8108'"]
      interval: 3s
      timeout: 5s
      retries: 3

  meilisearch0:
    image: getmeili/meilisearch:v1.12.0
    container_name: labrinth-meilisearch0
    restart: on-failure
    ports:
      - '127.0.0.1:7700:7700'
    volumes:
      - meilisearch-data:/data.ms
    environment:
      MEILI_MASTER_KEY: modrinth
      MEILI_HTTP_PAYLOAD_SIZE_LIMIT: 107374182400
      MEILI_LOG_LEVEL: warn
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:7700/health']
      interval: 3s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    container_name: labrinth-redis
    restart: on-failure
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'PING']
      interval: 3s
      timeout: 5s
      retries: 3

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: labrinth-clickhouse
    ports:
      - '127.0.0.1:8123:8123'
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
    healthcheck:
      test: ['CMD-SHELL', 'clickhouse-client --query "SELECT 1"']
      interval: 3s
      timeout: 5s
      retries: 3

  mail:
    image: axllent/mailpit:v1.27
    container_name: labrinth-mail
    ports:
      - '127.0.0.1:1025:1025'
      - '127.0.0.1:8025:8025'
    environment:
      MP_ENABLE_SPAMASSASSIN: postmark
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '-q',
          '-O/dev/null',
          'http://localhost:8025/api/v1/info',
        ]
      interval: 3s
      timeout: 5s
      retries: 3

  labrinth:
    build:
      context: .
      dockerfile: ./apps/labrinth/Dockerfile
    container_name: labrinth
    ports:
      - '8000:8000'
    env_file: ./apps/labrinth/.env.docker-compose
    environment:
      - DATABASE_URL=postgresql://labrinth:labrinth@postgres_db/labrinth
      - REDIS_URL=redis://redis:6379
      - CLICKHOUSE_URL=http://clickhouse:8123
      - TYPESENSE_URL=http://typesense0:8108
      - MEILISEARCH_READ_ADDR=http://meilisearch0:7700
      - MEILISEARCH_WRITE_ADDRS=http://meilisearch0:7700
    volumes:
      - labrinth-cdn-data:/tmp/modrinth
    depends_on:
      postgres_db:
        condition: service_healthy
      meilisearch0:
        condition: service_healthy
      typesense0:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      mail:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    environment:
      - BROWSER_BASE_URL=https://api.modrinth.com/v2/
      - PYRO_BASE_URL=http://localhost:8000/
    depends_on:
      - labrinth

volumes:
  typesense-data:
  meilisearch-data:
  db-data:
  redis-data:
  labrinth-cdn-data:
